import { formatZar, periodLabel } from './defaults'
import { GLORIA_LOGO_DATAURL } from './logo'
import type { Payslip, Staff } from './types'

function esc(s: string): string {
  return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

/** A BCEA-style payslip: employer + employee details, earnings, deductions, net pay. */
export function renderPayslipHtml(p: Payslip, staff: Staff | null, storeName: string): string {
  const rows = (lines: { label: string; amount: number }[]): string =>
    lines
      .map((l) => `<tr><td>${esc(l.label)}</td><td class="num">${formatZar(l.amount)}</td></tr>`)
      .join('')
  const totalDeductions = p.paye + p.uif + p.other_deductions

  return `<!doctype html><html lang="en"><head><meta charset="utf-8" />
<title>Payslip — ${esc(p.staff_name)} — ${esc(p.period)}</title>
<style>
  :root{--brown:#4b2e2e;--accent:#8b5e34;--cream:#f7f3ee;--ink:#1f2937;--muted:#6b7280;--line:#e5e7eb;}
  *{box-sizing:border-box;} body{font-family:'Segoe UI',system-ui,sans-serif;color:var(--ink);margin:0;padding:44px;background:#fff;}
  .sheet{max-width:760px;margin:0 auto;}
  header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid var(--accent);padding-bottom:14px;}
  .logo{height:54px;display:block;margin-bottom:8px;}
  .co{font-size:12px;color:var(--muted);line-height:1.5;} .co b{color:var(--brown);font-size:14px;}
  h1{color:var(--brown);font-size:22px;margin:0;text-align:right;} .meta{font-size:12.5px;color:var(--muted);text-align:right;margin-top:4px;}
  .who{display:grid;grid-template-columns:1fr 1fr;gap:8px 24px;margin:18px 0;font-size:12.5px;}
  .who .lbl{font-size:10px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted);}
  .who .val{color:var(--ink);font-weight:600;}
  .cols{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:8px;}
  table{width:100%;border-collapse:collapse;} th,td{padding:7px 10px;font-size:13px;text-align:left;}
  thead th{background:var(--brown);color:var(--cream);font-weight:600;} td.num,th.num{text-align:right;font-variant-numeric:tabular-nums;}
  tbody td{border-bottom:1px solid var(--line);} tfoot td{border-top:2px solid var(--brown);font-weight:700;color:var(--brown);}
  .net{margin-top:18px;display:flex;justify-content:space-between;align-items:center;background:var(--brown);color:var(--cream);padding:14px 18px;border-radius:6px;}
  .net .amt{font-size:24px;font-weight:800;}
  .foot{margin-top:22px;font-size:10.5px;color:var(--muted);border-top:1px solid var(--line);padding-top:8px;}
  @media print{body{padding:0;} thead th,.net{-webkit-print-color-adjust:exact;print-color-adjust:exact;}}
</style></head><body><div class="sheet">
  <header>
    <div><img class="logo" src="${GLORIA_LOGO_DATAURL}" alt="logo" /><div class="co"><b>${esc(storeName)}</b><br>707 Currie Road, Windermere, Durban<br>VAT 4470291941</div></div>
    <div><h1>PAYSLIP</h1><div class="meta">Pay period: <b>${esc(periodLabel(p.period))}</b></div></div>
  </header>

  <div class="who">
    <div><div class="lbl">Employee</div><div class="val">${esc(p.staff_name)}</div></div>
    <div><div class="lbl">Occupation</div><div class="val">${esc(staff?.occupation || '—')}</div></div>
    <div><div class="lbl">ID number</div><div class="val">${esc(staff?.id_number || '—')}</div></div>
    <div><div class="lbl">Tax number</div><div class="val">${esc(staff?.tax_number || '—')}</div></div>
    <div><div class="lbl">Bank</div><div class="val">${esc(staff?.bank_name || '—')}${staff?.bank_account ? ' · ' + esc(staff.bank_account) : ''}</div></div>
    <div><div class="lbl">Status</div><div class="val">${esc(staff?.status || '—')}</div></div>
  </div>

  <div class="cols">
    <table>
      <thead><tr><th>Earnings</th><th class="num">Amount</th></tr></thead>
      <tbody>${rows(p.earnings)}</tbody>
      <tfoot><tr><td>Gross</td><td class="num">${formatZar(p.gross)}</td></tr></tfoot>
    </table>
    <table>
      <thead><tr><th>Deductions</th><th class="num">Amount</th></tr></thead>
      <tbody>${rows(p.deductions)}</tbody>
      <tfoot><tr><td>Total</td><td class="num">${formatZar(totalDeductions)}</td></tr></tfoot>
    </table>
  </div>

  <div class="net"><span>NET PAY</span><span class="amt">${formatZar(p.net)}</span></div>

  <p class="foot">
    Employer contributions (not deducted from you): UIF ${formatZar(p.uif_employer)} · SDL ${formatZar(p.sdl)}.
    PAYE &amp; UIF calculated per SARS ${esc(p.period.slice(0, 4))} tables. Generated by Cafe Studio.
  </p>
</div></body></html>`
}
