import { formatZar, periodLabel } from './defaults'
import { GLORIA_BRAND, brandCss, brandFontLink, brandHeader, type Brand } from './brand'
import type { Payslip, Staff } from './types'

function esc(s: string): string {
  return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

/** A BCEA-style payslip in the active brand's identity: employer + employee
 *  details, earnings, deductions, net pay. */
export function renderPayslipHtml(
  p: Payslip,
  staff: Staff | null,
  storeName: string,
  brand: Brand = GLORIA_BRAND
): string {
  const rows = (lines: { label: string; amount: number }[]): string =>
    lines
      .map((l) => `<tr><td>${esc(l.label)}</td><td class="num">${formatZar(l.amount)}</td></tr>`)
      .join('')
  const totalDeductions = p.paye + p.uif + p.other_deductions

  return `<!doctype html><html lang="en"><head><meta charset="utf-8" />
<title>Payslip — ${esc(p.staff_name)} — ${esc(p.period)}</title>
${brandFontLink(brand)}
<style>${brandCss(brand)}
  .sheet{max-width:760px;}
  .who{display:grid;grid-template-columns:1fr 1fr;gap:8px 24px;margin:18px 0;font-size:12.5px;}
  .who .val{color:var(--ink);font-weight:600;}
  .cols{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:8px;}
  .net{margin-top:18px;display:flex;justify-content:space-between;align-items:center;padding:14px 18px;}
  .net .amt{font-size:24px;font-weight:800;}
  .foot{margin-top:22px;font-size:10.5px;color:var(--muted);border-top:1px solid var(--line);padding-top:8px;}
</style></head><body><div class="sheet">
  ${brandHeader(
    brand,
    'Payslip',
    `Pay period: <b>${esc(periodLabel(p.period))}</b>`,
    `<b>${esc(storeName)}</b><br>${esc(brand.address)}<br>VAT ${esc(brand.vatNo)}`
  )}

  <div class="who">
    <div><div class="lbl">Employee</div><div class="val">${esc(p.staff_name)}</div></div>
    <div><div class="lbl">Occupation</div><div class="val">${esc(staff?.occupation || '—')}</div></div>
    <div><div class="lbl">ID number</div><div class="val">${esc(staff?.id_number || '—')}</div></div>
    <div><div class="lbl">Tax number</div><div class="val">${esc(staff?.tax_number || '—')}</div></div>
    <div><div class="lbl">Bank</div><div class="val">${esc(staff?.bank_name || '—')}${staff?.bank_account ? ' · ' + esc(staff.bank_account) : ''}</div></div>
    <div><div class="lbl">Status</div><div class="val">${esc(staff?.status || '—')}</div></div>
  </div>

  <div class="cols">
    <table>
      <thead><tr><th>Earnings</th><th class="num">Amount</th></tr></thead>
      <tbody>${rows(p.earnings)}</tbody>
      <tfoot><tr><td>Gross</td><td class="num">${formatZar(p.gross)}</td></tr></tfoot>
    </table>
    <table>
      <thead><tr><th>Deductions</th><th class="num">Amount</th></tr></thead>
      <tbody>${rows(p.deductions)}</tbody>
      <tfoot><tr><td>Total</td><td class="num">${formatZar(totalDeductions)}</td></tr></tfoot>
    </table>
  </div>

  <div class="net hero"><span>NET PAY</span><span class="amt">${formatZar(p.net)}</span></div>

  <p class="foot">
    Employer contributions (not deducted from you): UIF ${formatZar(p.uif_employer)} · SDL ${formatZar(p.sdl)}.
    PAYE &amp; UIF calculated per SARS ${esc(p.period.slice(0, 4))} tables. Generated by Cafe Studio.
  </p>
</div></body></html>`
}
