import { formatZar } from './defaults'
import { GLORIA_BRAND, brandCss, brandFontLink, brandHeader, type Brand } from './brand'
import type { StatementView } from './types'

function esc(s: string): string {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

/** Renders a per-store Statement of Account in the active brand's identity. */
export function renderStatementHtml(v: StatementView, brand: Brand = GLORIA_BRAND): string {
  const acct = v.account
  const rows = v.lines
    .map(
      (l, i) => `
      <tr${i % 2 ? ' class="alt"' : ''}>
        <td>${esc(l.line_date)}</td>
        <td>${l.tx_type === 'payment' ? 'Payment Received' : 'Invoice'}</td>
        <td>${esc(l.details)}</td>
        <td class="num">${l.debit ? formatZar(l.debit) : ''}</td>
        <td class="num">${l.credit ? formatZar(l.credit) : ''}</td>
        <td class="num">${formatZar(l.balance ?? 0)}</td>
      </tr>`
    )
    .join('')

  return `<!doctype html><html lang="en"><head><meta charset="utf-8" />
<title>Statement of Account — ${esc(v.storeName)} — ${esc(v.periodLabel)}</title>
${brandFontLink(brand)}
<style>${brandCss(brand)}
  .sheet{max-width:920px;}
  h1{text-transform:none;}
  .period{color:var(--muted);font-size:15px;text-align:right;}
  .parties{display:flex;justify-content:space-between;gap:24px;margin:22px 0;}
  .cust{font-size:13.5px;line-height:1.5;}
  .summary{border:1px solid var(--line);border-radius:10px;padding:14px 18px;min-width:280px;}
  .summary h2{font-size:12px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted);margin:0 0 8px;}
  .summary .row{display:flex;justify-content:space-between;font-size:14px;padding:3px 0;}
  .summary .bal{border-top:2px solid var(--primary);margin-top:6px;padding-top:8px;font-weight:700;color:var(--ink);font-size:16px;}
  td:last-child{font-weight:600;}
  footer{margin-top:24px;color:#9ca3af;font-size:11px;border-top:1px solid var(--line);padding-top:12px;}
</style></head><body><div class="sheet">
  ${brandHeader(
    brand,
    'Statement of Account',
    `To ${esc(v.periodLabel || '')}`,
    `<b>${esc(brand.legalName)}</b><br>${esc(brand.address)}<br>${esc(brand.postal)}<br>${esc(brand.email)} · VAT ${esc(brand.vatNo)}`
  )}
  <div class="parties">
    <div class="cust">
      <div class="lbl">Account</div>
      <div><strong>${esc(acct?.customer_name || v.storeName)}</strong></div>
      ${acct?.address ? `<div>${esc(acct.address)}</div>` : ''}
      ${acct?.vat_no ? `<div>VAT: ${esc(acct.vat_no)}</div>` : ''}
    </div>
    <div class="summary">
      <h2>Account Summary</h2>
      <div class="row"><span>Invoiced Amount</span><span>${formatZar(v.summary.invoiced)}</span></div>
      <div class="row"><span>Amount Paid</span><span>${formatZar(v.summary.paid)}</span></div>
      <div class="row bal"><span>Balance Due</span><span>${formatZar(v.summary.balance)}</span></div>
    </div>
  </div>
  <table>
    <thead><tr><th>Date</th><th>Transaction</th><th>Details</th><th class="num">Debit</th><th class="num">Credit</th><th class="num">Balance</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="6" style="text-align:center;color:#9ca3af;padding:20px">No transactions.</td></tr>'}</tbody>
  </table>
  <footer>Generated by Cafe Studio · ${esc(v.storeName)} · ${new Date().toLocaleDateString('en-ZA', { dateStyle: 'long' })}</footer>
</div></body></html>`
}
